yahoo:
  client:
    clientId: dj0yJmk9N0NQckJkZWVoc2RoJmQ9WVdrOU1qRktSR2RNTjJzbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD0xNA--
    clientSecret: a98cba405f2d17da1f7128621cdd0d6316a9cf94
    accessTokenUri: https://api.login.yahoo.com/oauth2/get_token
    userAuthorizationUri: https://api.login.yahoo.com/oauth2/request_auth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://social.yahooapis.com/v1/me/guid
server:
  port: 80